#!/usr/bin/env node

var
	fs = require('fs-extra'),
	postcss = require('postcss')
;

//fs.emptyDirSync('dist');

master();
base();
customScrollbarOptiScroll();

function master() {
	fs.copySync('src/index.html', 'dist/index.html');

	var input = fs.readFileSync('src/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/'
		}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
}


function base() {
	fs.emptyDirSync('dist/base');

	fs.copySync('src/base/index.html', 'dist/base/index.html');

	var input = fs.readFileSync('src/base/css/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/base/css'
		}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/base/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
}

function customScrollbarOptiScroll() {
	//var demo = 'customScrollbarOptiScroll';

	fs.emptyDirSync('dist/custom-scrollbar-optiscroll');

	fs.copySync('src/custom-scrollbar-optiscroll/index.html', 'dist/custom-scrollbar-optiscroll/index.html');
	fs.copySync('src/custom-scrollbar-optiscroll/js/', 'dist/custom-scrollbar-optiscroll/js');

	var input = fs.readFileSync('src/custom-scrollbar-optiscroll/css/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/custom-scrollbar-optiscroll/css'}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/custom-scrollbar-optiscroll/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});

}
