#!/usr/bin/env node

var
	fs = require('fs-extra'),
	postcss = require('postcss')
;

//fs.emptyDirSync('dist');

master();
base();
customScrollbarOptiScroll();
slidein();

function master() {
	var input = fs.readFileSync('src/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/'
		}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
}


function base() {
	fs.emptyDirSync('dist/fixed-default-scrollbar');

	fs.copySync('src/fixed-default-scrollbar/index.html', 'dist/fixed-default-scrollbar/index.html');

	var input = fs.readFileSync('src/fixed-default-scrollbar/css/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/fixed-default-scrollbar/css'
		}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/fixed-default-scrollbar/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
}

function slidein() {
	fs.emptyDirSync('dist/slidein-top-optiscroll');

	fs.copySync('src/slidein-top-optiscroll/index.html', 'dist/slidein-top-optiscroll/index.html');
	fs.copySync('src/slidein-top-optiscroll/js/', 'dist/slidein-top-optiscroll/js');

	var input = fs.readFileSync('src/slidein-top-optiscroll/css/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src/fixed-custom-scrollbar-optiscroll/css'}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('postcss-color-gray')(),
		require('autoprefixer-core')()
	])
	.process(input, {
		//from: 'src/app.css',
		//to: 'app.css'
	})
	.then(function(result) {
		fs.outputFileSync('dist/slidein-top-optiscroll/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
	});
}

	function customScrollbarOptiScroll() {
		//var demo = 'customScrollbarOptiScroll';

		fs.emptyDirSync('dist/fixed-custom-scrollbar-optiscroll');

		fs.copySync('src/fixed-custom-scrollbar-optiscroll/index.html', 'dist/fixed-custom-scrollbar-optiscroll/index.html');
		fs.copySync('src/fixed-custom-scrollbar-optiscroll/js/', 'dist/fixed-custom-scrollbar-optiscroll/js');

		var input = fs.readFileSync('src/fixed-custom-scrollbar-optiscroll/css/style.css', 'utf8');

		postcss([
			require('postcss-inline-comment')(),
			require('postcss-import')({
				path: 'src/fixed-custom-scrollbar-optiscroll/css'}),
			require('postcss-custom-properties')(),
			require('postcss-calc')({
				preserve: false,
				precision: 5
			}),
			require('postcss-color-gray')(),
			require('autoprefixer-core')()
		])
		.process(input, {
			//from: 'src/app.css',
			//to: 'app.css'
		})
		.then(function(result) {
			fs.outputFileSync('dist/fixed-custom-scrollbar-optiscroll/css/style.css', result.css); //fs.writeFileSync('dist/style.css', result.css);
		});
}
